name: CI

on:
  pull_request:
    branches:
    - dev
    - stg
    - prd

env:
  targetBranch: ${{ github.event.pull_request.base.ref }}
  workingDirectory: ${{ github.event.pull_request.base.ref == 'prd' && './terraform/prd' || './terraform/stg'}} # else block is stg, that's ok because only dev, stg, and prd trigger the workflow

jobs:

  path-filter:
    name: Setup Path Filter
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      terraform: ${{ steps.filter.outputs.terraform }}
    steps:
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: | # purposefully exclude README and LICENSE
          changes:
            - 'terraform/**'

  terraform-plan:
    name: 'Terraform Plan'
    needs: [path-filter]
    if: ${{ needs.path-filter.outputs.terraform == 'true'}}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

    # configure credentials
    - name: Configure AWS Credentials (stg)
      if: ${{ env.targetBranch == 'dev' || env.targetBranch == 'stg' }}
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: us-west-1
        role-to-assume: ${{ secrets.IAM_ROLE_ARN_STG }}
        role-session-name: gha-session

    - name: Configure AWS Credentials (prd)
      if: ${{ env.targetBranch == 'prd' }}
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: us-west-1
        role-to-assume: ${{ secrets.IAM_ROLE_ARN_PRD }}
        role-session-name: gha-session

    # checkout the repo
    - name: Checkout
      uses: actions/checkout@v6

    # install terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    # run terraform
    - name: Terraform Init
      working-directory: ${{ env.workingDirectory }}
      run: terraform init

    - name: Terraform Format
      working-directory: ${{ env.workingDirectory }}
      run: terraform fmt -recursive -check

    - name: Terraform Plan
      working-directory: ${{ env.workingDirectory }}
      run: terraform plan
